stages:


- stage: BuildServices

  pool:
    vmImage: ubuntu-latest  
  jobs:
    - job: BuildDocker_SalesBookWEB
      displayName: Build Docker Image fo SalesBook.WEB app

      steps:
      - task: Docker@2
        inputs:
            containerRegistry: 'crmeritosSvcConnection'
            repository: 'SalesBook.WEB'
            command: 'buildAndPush'
            Dockerfile: '**/SalesBook.WEB/Dockerfile'
            tags: |
                $(Build.BuildId)
                latest

    - job: BuildDocker_SalesBookLB
      displayName: Build Docker Image fo SalesBook.LB app
      
      steps:
      - task: Docker@2
        inputs:
            containerRegistry: 'crmeritosSvcConnection'
            repository: 'SalesBook.LB'
            command: 'buildAndPush'
            Dockerfile: '**/SalesBook.LB/Dockerfile'
            tags: |
                $(Build.BuildId)
                latest

- stage: DeploytoAKS
    
  pool:
    vmImage: ubutnu-latest
  jobs:
  - job: DeplytoAKS
    displayName: Deploy to AKS
    steps:
