stages:

- stage: BuildServices

  pool:
    vmImage: ubutnu-latest  
  jobs:
    - job: BuildDocker_SalesBookLB
      displayName: Build Docker Image fo SalesBook.LB app

      steps:
      - task: Docker@2
        inputs:
            command: 'buildAndPush'
            Dockerfile: '**/SalesBook.LB/Dockerfile'
            tags: |
                $(Build.BuildId)
                latest
